const ArrayEncode = require('./ArrayEncode.js');


const drawing_TULSA = [
  'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA', '////HgAPA+AAA//AAD8A',
  '////HgAPA+AAB//wAH8A', '////HgAPA+AAD//wAH8A', 'AD4AHgAPA+AAH//wAH+A',
  'AD4AHgAPA+AAPwDwAP+A', 'AD4AHgAPA+AAPgAwAP+A', 'AD4AHgAPA+AAPgAAAffA',
  'AD4AHgAPA+AAPgAAAffA', 'AD4AHgAPA+AAPgAAAePg', 'AD4AHgAPA+AAPgAAA+Pg',
  'AD4AHgAPA+AAP4AAA+Hg', 'AD4AHgAPA+AAH/gAA8Hw', 'AD4AHgAPA+AAD/+AB8Hw',
  'AD4AHgAPA+AAB//gB8Dw', 'AD4AHgAPA+AAAf/wD4D4', 'AD4AHgAPA+AAAA/4D4D4',
  'AD4AHgAPA+AAAAH4D4B8', 'AD4AHgAPA+AAAAD8H//8', 'AD4AHwAfA+AAAAB8H//8',
  'AD4AHwAfA+AAAAB8H//+', 'AD4AHwAfA+AAAAB8PgA+', 'AD4AH4A/A+AAOAD8PgAf',
  'AD4AD8B+A+AAPgH4fAAf', 'AD4AD//+A+AAP//4fAAf', 'AD4AB//8A///P//wfAAP',
  'AD4AA//4A///P//g+AAP', 'AD4AAP/gA///B/+A+AAP', 'AAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA',
  '////HgAPA+AAA//AAD8A', '////HgAPA+AAB//wAH8A', '////HgAPA+AAD//wAH8A',
  'AD4AHgAPA+AAH//wAH+A', 'AD4AHgAPA+AAPwDwAP+A', 'AD4AHgAPA+AAPgAwAP+A',
  'AD4AHgAPA+AAPgAAAffA', 'AD4AHgAPA+AAPgAAAffA', 'AD4AHgAPA+AAPgAAAePg',
  'AD4AHgAPA+AAPgAAA+Pg', 'AD4AHgAPA+AAP4AAA+Hg', 'AD4AHgAPA+AAH/gAA8Hw',
  'AD4AHgAPA+AAD/+AB8Hw', 'AD4AHgAPA+AAB//gB8Dw', 'AD4AHgAPA+AAAf/wD4D4',
  'AD4AHgAPA+AAAA/4D4D4', 'AD4AHgAPA+AAAAH4D4B8', 'AD4AHgAPA+AAAAD8H//8',
  'AD4AHwAfA+AAAAB8H//8', 'AD4AHwAfA+AAAAB8H//+', 'AD4AHwAfA+AAAAB8PgA+',
  'AD4AH4A/A+AAOAD8PgAf', 'AD4AD8B+A+AAPgH4fAAf', 'AD4AD//+A+AAP//4fAAf',
  'AD4AB//8A///P//wfAAP', 'AD4AA//4A///P//g+AAP', 'AD4AAP/gA///B/+A+AAP',
  'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA'
];


function toArrayOfArrays(drawing) {
  return drawing.map(line => line.split('').map(x => Number(x)));
}


function toEncoded(drawing) {
  const arr = toArrayOfArrays(drawing);
  return arr.map(lineArray => ArrayEncode(lineArray));
}


module.exports = [ drawing_TULSA ];
