const ArrayEncode = require('./ArrayEncode.js');


const drawing_TULSA = [
  'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA',
  'P/8GcB/weAH/+DOA/4PA', 'A4cGcD/weAAcODOB/4PA', 'A4cGcDhw+AAcODOBw4fA',
  'A4cGcDgA/AAcODOBwAfg', 'A4cGcDwB3AAcODOB4A7g', 'A4cGcD/hzgAcODOB/w5w',
  'A4cGcA/xjgAcODOAf4xw', 'A4cGcADz/gAcODOAB5/w', 'A4cGcABzhwAcODOAA5w4',
  'A4cOcDBzBwAcOHOBg5g4', 'A4P+cD/3AwAcH/OB/7gY', 'A4H8f//nA4AcD+P//zgc',
  'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAA', 'P/8GcB/weAH/+DOA/4PA', 'A4cGcD/weAAcODOB/4PA',
  'A4cGcDhw+AAcODOBw4fA', 'A4cGcDgA/AAcODOBwAfg', 'A4cGcDwB3AAcODOB4A7g',
  'A4cGcD/hzgAcODOB/w5w', 'A4cGcA/xjgAcODOAf4xw', 'A4cGcADz/gAcODOAB5/w',
  'A4cGcABzhwAcODOAA5w4', 'A4cOcDBzBwAcOHOBg5g4', 'A4P+cD/3AwAcH/OB/7gY',
  'A4H8f//nA4AcD+P//zgc', 'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA', 'P/8GcB/weAH/+DOA/4PA',
  'A4cGcD/weAAcODOB/4PA', 'A4cGcDhw+AAcODOBw4fA', 'A4cGcDgA/AAcODOBwAfg',
  'A4cGcDwB3AAcODOB4A7g', 'A4cGcD/hzgAcODOB/w5w', 'A4cGcA/xjgAcODOAf4xw',
  'A4cGcADz/gAcODOAB5/w', 'A4cGcABzhwAcODOAA5w4', 'A4cOcDBzBwAcOHOBg5g4',
  'A4P+cD/3AwAcH/OB/7gY', 'A4H8f//nA4AcD+P//zgc', 'AAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA',
  'AAAAAAAAAAAAAAAAAAAA', 'AAAAAAAAAAAAAAAAAAAA'
];


function toArrayOfArrays(drawing) {
  return drawing.map(line => line.split('').map(x => Number(x)));
}


function toEncoded(drawing) {
  const arr = toArrayOfArrays(drawing);
  return arr.map(lineArray => ArrayEncode(lineArray));
}


module.exports = [ drawing_TULSA ];
